proposals/simd/SIMD.md

This is relevant for the sub_saturate_u operations.
Fixes #15.

Saturate negative numbers to 0.

---

proposals/simd/SIMD.md

Fixes #12.
The effect of these dynamic constructors can be achieved with an S.const
instruction followed by a sequence of S.replaceLane instructions. This
is also what LLVM does.

Remove the S.build(...) constructors.

---

proposals/simd/SIMD.md

This is already stated at the beginning of the "Operations" section, but it is worth restating it again in the "Comparisons" sub-section.
Closes #45 .

State result value of comparisons

---

proposals/simd/SIMD.md

Default to full IEEE 754 support for now. The issue of handling subnormals needs to be addressed (possibly by a global FTZ flag or mode switching), but allowing platforms to behave differently on FTZ semantics should not be baked into the specification.

Remove text about flushing of subnormals

---

proposals/simd/SIMD.md

This makes it clear everywhere that `ImmLaneIdx` is an immediate operand and also makes the nomenclature for immediate operands consistent (both `ImmByte` and `ImmLaneIdx`  start with the prefix `Imm`) .
See https://github.com/WebAssembly/simd/issues/33 .

Rename LaneIdx{2,4,8,16,32} to ImmLaneIdx{2,4,8,16,32}

---

proposals/simd/SIMD.md
proposals/simd/TextSIMD.md

v128.const text

---

proposals/simd/TextSIMD.md

Separate each lane index because they are always interpreted
independently.

Specify v8x16.shuffle text format

---

proposals/simd/BinarySIMD.md
proposals/simd/SIMD.md
proposals/simd/TextSIMD.md

This change adds a dynamic permute instruction to SIMD proposal.
~~The name "permute", as opposed to shuffle, is used to distinguish it from
instructions that operate on two input vectors.~~
When indices are out of range, the result is specified as 0 for each
lane. This matches hardware behavior on ARM and RISCV architectures.
On x86_64 and MIPS, the hardware provides instructions that can select 0
when the high bit is set to 1 (x86_64) or any of the two high bits are
set to 1 (MIPS). On these architectures, the backend is expected to emit
a pair of instructions, saturating byte add (`saturate(x + (128 - 16))` for
x86_64) and permute, to emulate the proposed behavior.
Fixes #68.
Contributes to #24.
Fixes #11.

Add v8x16.shuffle1 instruction and rename v8x16.shuffle to v8x16.shuffle2_imm

---

proposals/simd/BinarySIMD.md
proposals/simd/ImplementationStatus.md
proposals/simd/SIMD.md

Loading a single element into all lanes of a SIMD vector is a common operation in signal processing, and both ARM NEON and recent x86 SIMD extensions can do it in a single instruction. In currently WebAssembly SIMD proposal this operation can be emulated via a combination of a scalar load and a `splat` instruction to replace the loaded scalar value into all lanes of a SIMD register. Unlike LLVM, streaming compilers in WebAssembly engines generate code under tight latency constraints, and can not afford pattern matching to generate optimal machine instruction for the combination of load and splat WAsm instructions. **This PR introduce combined Load-and-Splat instructions which offer two advantages improvements over the above two-instruction combination**:
1. The value from memory is loaded …

Add Load-And-Splat instructions

---

proposals/simd/SIMD.md

Issue in Shuffle
s/result[i] = b[s[i] - S.lanes]/result[i] = b[s[i] - S.lanes
Issue in Bit Shifts
s/def S.shl(a, x):/def S.shl(a, y):

Minor Documentation Fixes

---

proposals/simd/BinarySIMD.md
proposals/simd/ImplementationStatus.md
proposals/simd/SIMD.md

This is consistent with other instructions like `v8x16.swizzle` and `v8x16.shuffle` that can be defined as operating on uninterpreted bit strings rather than integers or floats.

Rename load-and-splat instructions from iNxM.load_splat to vNxM.load_splat

---

proposals/simd/SIMD.md

This is what the SSE `packuswb` and `packusdw` instructions do, so I'm guessing that's how these instructions are supposed to work?

Clarify that the SIMD narrowing instructions interpret their inputs as signed integers

---

proposals/simd/SIMD.md

Clarify that shift count is modulo lane width

---

proposals/simd/SIMD.md

Clarifies that low lanes are lanes `[0, n/2)` and high lanes are
`[n/2, n)` and that the order of arguments to the narrowing ops
are (low, high). This matches the current implementation in V8.
Resolves #103.

Add pseudocode for widening and narrowing operations

---

proposals/simd/BinarySIMD.md
proposals/simd/ImplementationStatus.md
proposals/simd/SIMD.md

This is consistent with the ordering for all other instructions that
have signed and unsigned variants. This does renumber these
instructions, but no engine or toolchain has documented support for
these instructions yet, so that should be ok.

Reorder extending loads to have signed variants first

---

proposals/simd/BinarySIMD.md
proposals/simd/ImplementationStatus.md
proposals/simd/SIMD.md

Introduction
=========
ANDNOT is a widely supported SIMD operation which computes `a & ~b`. ANDNOT is involved in a common idiom of zeroing out elements which don't satisfy a condition, i.e.
```c
float x = ...;
const bool cond = ...;
if (!cond) x = 0;
```
In the present SIMD instruction set, a vectorized version of this snippet would require two WAsm SIMD instructions, `v128.and` and `v128.not`:
```c
v128 x = ...;
const v128 cond = ...;
x = v128.and(x, v128.not(cond));
```
Representing ANDNOT as two instructions is inefficient on all architectures:
- On ARM, ARM64, and PowerPC it requires two machine instructions even though ANDNOT has an exact equivalent in their SIMD instruction sets.
- On x86 and x86-64 it requires three machine instructions because x86 SIMD extensions (until AVX512) …

ANDNOT operation

---

proposals/simd/BinarySIMD.md
proposals/simd/ImplementationStatus.md
proposals/simd/SIMD.md

A poll was held at CG meeting today, the consensus was for Option 3 of
https://github.com/WebAssembly/simd/issues/101.
This means we have all the f64x2 instructions, and some of the more
common i64x2 that have been benchmarked. This change reflects that
option in the proposal text, binary text, and implementation status.
Fixes #101.

Update 64x2 instructions

---

test/core/simd/simd_const.wast

New tests for 64x2 constant and more literal
testing per https://github.com/WAVM/WAVM/issues/195

[test] Integrate latest v128 constant tests

---

proposals/simd/SIMD.md

Introducing pseudocode for memory operations.

Add Python pseudocode to memory operations

---

interpreter/binary/encode.ml
interpreter/exec/eval_numeric.ml
interpreter/exec/v128.ml
interpreter/exec/vector.ml
interpreter/host/spectest.ml
interpreter/runtime/memory.ml
interpreter/script/js.ml
interpreter/syntax/ast.ml
interpreter/syntax/types.ml
interpreter/syntax/values.ml
interpreter/text/arrange.ml
interpreter/text/lexer.mll
interpreter/valid/valid.ml

Provide a buildable skeleton for the interpereter, with end-to end
types, but with lots of gaps in functionality. Unimplemented functions
throw "TODO v128" error; can parse `v128` local type and nothing more.

[Interpreter] infrastructure

---

README.md

Nit: Change calling the semantics description the "proposed specification", to avoid confusion with the actual specification document.

Clarification in README

---

test/core/simd/meta/simd.py
test/core/simd/meta/simd_arithmetic.py
test/core/simd/meta/simd_bitwise.py
test/core/simd/meta/simd_f32x4.py
test/core/simd/meta/simd_f32x4_arith.py
test/core/simd/meta/simd_f64x2.py
test/core/simd/meta/simd_f64x2_arith.py
test/core/simd/meta/simd_f64x2_cmp.py
test/core/simd/meta/simd_sat_arith.py
test/core/simd/meta/test_assert.py

https://github.com/WAVM/WAVM/pull/223
[simd] Improve simd test generation tool
- Use names in the string interpolation so its clear
what each part is supposed to be.
- Use unified naming converson for params.

[test] Sync tests from WAVM#223

---

proposals/simd/BinarySIMD.md
proposals/simd/ImplementationStatus.md
proposals/simd/SIMD.md

Introduction
=========
Rounding Average of two integer inputs, defined as `avg(a, b) := (a + b + 1) >> 1`, is a common operation in fixed-point numerical algorithms, such as video- and audio-codecs, and image filtering. Direct implementation of Rounding Average in SIMD instruction sets following the formula `(a + b + 1) >> 1` is tricky, because while the sum `a + b + 1` can overflow the datatype of inputs, the final result always fits into the same datatype. To avoid the expensive work-around of computing `a + b + 1` in higher precision (e.g. extending inputs from 8-bit elements to 16-bit elements for the computation), all common SIMD instruction sets provide some forms of Rounding Average instructions.
This PR introduce two new WebAssembly instructions for Rounding Average operations, …

Rounding Average instructions

---

proposals/simd/SIMD.md

Previously it was not clear what to do when passing an `i32` to, e.g., an `i8x16.splat`: the `i32` has more bits than fit in an `i8` lane. As discussed in #149, this change removes the extra bits (potentially losing information) so that the input parameter will fit in the splatted lanes. If at some point the spec adds support for `i8` and `i16` types, then this change would be unnecessary since the splat signature could be, e.g., `i8x16.splat(x: i8)` and no truncation would be required.

Truncate extra bits of too-large parameters to splat; closes #149

---

test/core/simd/simd_lane.wast

This updates a few of the assertions in `simd_lane.wast` found after writing a parser which consumes `*.wast` files and choking on a few of the test cases here. I'm not 100% sure if all of these changes are correct, so feedback is appreciated!
Additionally, are these tests currently run through a reference implementation somewhere? I'm not sure if the spec interpreter in this repo has been updated for the tests yet.

Update some of the test assertions in `simd_lane.wast`

---

interpreter/exec/v128.ml

The bytes weren't set correct, because we were not scaling the index
properly.

Fix setting bytes when converting from string to V128

---

interpreter/binary/encode.ml
interpreter/exec/simd.ml
interpreter/exec/v128.ml

See https://github.com/WebAssembly/simd/blob/master/proposals/simd/BinarySIMD.md for binary encoding of v128 type and v128.const.

Add encoding for v128 type and v128.const

---

interpreter/exec/simd.ml
interpreter/exec/v128.ml

Following up from https://github.com/WebAssembly/simd/pull/170#discussion_r365121635

Change Rep type of SIMD to be immutable string

---

proposals/simd/BinarySIMD.md
proposals/simd/ImplementationStatus.md
proposals/simd/SIMD.md

In the SIMD sync on 2020-01-14, we discussed the challenges with
implementing these instructions in a performant way on 32-bit archs. And
even on 64-bit arch, like x64, it requires AVX-512 for good codegen.
There is consensus that because it is uncommon for such instructions to
be used, and that hardware support is not widespread, we can remove
these.

Remove i64x2 <-> f64x2 conversion opcodes

---

test/core/simd/simd_const.wast
test/core/simd/simd_lane.wast
test/core/simd/simd_load.wast

- Fix mistake tests in simd_load.wast
- Missing lane index should be malformed
- Test more values of lane index
Fix #181

[test] Fix issue #181

---

test/core/simd/simd_lane.wast

The `assert_invalid` directive isn't intended to be used with `(module
quote ...)` and the `module quote` part can be removed here as well
since the module should successfully parse, but fail to validate.

Adjust two more tests from recent changes

---

proposals/simd/BinarySIMD.md
proposals/simd/ImplementationStatus.md
proposals/simd/SIMD.md

Introduction
=========
Integer absolute value instructions are well-supported on the most popular architecture (on x86 since SSSE3, on ARM since the first version of NEON), and naturally complement floating-point absolute value instructions already existing in WebAssembly SIMD.
This PR introduce three new WebAssembly instructions for integer absolute value operations, `i8x16.abs`, `i16x8.abs`, and `i32x4.abs`, which operate on vectors of 8-bit, 16-bit, and 32-bit integers accordingly. 64-bit version is omitted due to lack of support in common SIMD instruction sets.
Mapping to Common Instruction Sets
===========================
This section illustrates how the new WebAssembly instructions can be lowered on common instruction sets. However, these patterns are provided only for convenience, …

Integer absolute value instructions

---

proposals/simd/ImplementationStatus.md

Unsure why this was marked as unimplemented but it definitely works in
Chrome stable.

Mark f32x4.sqrt as implemented in v8

---

test/core/simd/meta/simd_f32x4.py
test/core/simd/meta/simd_f64x2.py
test/core/simd/simd_f32x4.wast
test/core/simd/simd_f64x2.wast

Pulled from https://github.com/WAVM/WAVM/pull/269

[test] Fixed mismatched op names in comments

---

test/core/simd/meta/simd_arithmetic.py
test/core/simd/meta/simd_int_arith2.py
test/core/simd/meta/simd_integer_op.py

- Centeralize integer arithmetic ops in one place
- Remove LaneNumber class as which is duplicated with simd_lane_value.py
- No impact for generated tests
Pulled from https://github.com/WAVM/WAVM/pull/268

[test] Optimize test generation tool

---

test/core/simd/meta/simd_arithmetic.py
test/core/simd/meta/simd_f32x4.py
test/core/simd/meta/simd_f32x4_arith.py
test/core/simd/meta/simd_f64x2.py
test/core/simd/meta/simd_f64x2_cmp.py
test/core/simd/meta/simd_sat_arith.py

- Remove the duplicate methods to format AssertReturn statements in
multiple lines. Use the united format methods of AssertReturn class
in test_assert.py.
- Use more descriptive param names.
These files are pulled from https://github.com/WAVM/WAVM/pull/273

[test] Simplify the use of formatting AssertReturn statements

---

interpreter/binary/encode.ml
interpreter/exec/eval.ml
interpreter/exec/eval_numeric.ml
interpreter/exec/eval_numeric.mli
interpreter/exec/simd.ml
interpreter/exec/v128.ml
interpreter/syntax/ast.ml
interpreter/syntax/operators.ml
interpreter/text/arrange.ml
interpreter/text/lexer.mll
interpreter/text/parser.mly
interpreter/valid/valid.ml

Add f32x4 min, max, abs extract lane, and i32x4 extract lane as examples
of how SIMD operations can be implemented.
extract_lane operations are missing validation, which can be added in
future patches.
With this patch, we don't fully support running the test `simd_f32x4.wast` yet, due to missing parsing of the `result` token in scripts. In particular, right now we only support const literal or a single canonical/arithmetic NaN. We will need to add support for parsing v128.const containing literals and/or canonical/arithmetic NaN, this can be done in a future patch.

Add some f32x4 instructions

---

interpreter/text/lexer.mll

Classic newbie mistake of using != on strings. Plus I got the
conditional wrong - it should error if s is none of the valid simd
shapes.
Also have the error message a bit more verbose.

Fix string comparison

---

interpreter/script/js.ml
interpreter/script/run.ml
interpreter/script/script.ml
interpreter/text/arrange.ml
interpreter/text/parser.mly

Wrap existing `LitResult` and `NanResult` in a `ValueResult`, and create another case `SimdF32x4Result` to represent a f32x4 result. This allows us to parse v128.const containing literals and/or nans without any recursive types.
This is in contrast to #217 which makes `result'` recursive, and so some functions in `run.ml` have to be changed to recursive.
I had to move the parsing of v128_const rule out of const, to avoid a shift reduce conflict in the `result :` rule.

Parse v128.const of nans in result_list of assert_return by wrapping existing result type

---

proposals/simd/ImplementationStatus.md

Updates based on latest LLVM & latest v8 (earlier v8 versions aren't
useful because of renumbering anyway):
- v8 implements load_splat and load with zero/sign extension
- v8 implements i64x2_mul
- v8 implements swizzle and andnot
- LLVM supports integer abs instructions and intrinsics
- Removing note about shuffle opcode - irrelevant post-renumbering
Notable remaining omissions:
- v8 doesn't implement v128.const
- LLVM doesn't implement (or at least doesn't expose an intrinsic for)
i64x2_mul
- A lot of instructions are still part of unimplemented subset in LLVM

Update ImplementationStatus to reflect status quo

---

proposals/simd/BinarySIMD.md
proposals/simd/ImplementationStatus.md
proposals/simd/NewOpcodes.md
proposals/simd/SIMD.md

A class of SIMD operations requires to perform processing in vector registers first, and then post-process some of the lanes using scalar code. Often this involves doing a vectorized comparison, followed by inspection of the lanes of the comparison mask.
This can be done using lane extraction, but it's usually slow - for example, in a vectorized memchr implementation, if any of the lanes compare as equal to the pattern, we need to quickly find the right lane.
This proposal suggests adding three new instruction that can faciliate this operation - they take all high bits from the lanes of the input vector and concatenate it into the scalar mask. The resulting mask can then be used with ctz instructions to find the first matching element, or as a table lookup index / for other needs.
See …

Add .bitmask instruction family

---

interpreter/exec/eval_numeric.ml
interpreter/exec/simd.ml
interpreter/exec/v128.ml

This does little right now, but will make it easier when we add more
SIMD int ops later (similar to MakeFloat).

Create a functor MakeInt (similar to MakeFloat)

---

test/core/simd/meta/simd_f64x2.py
test/core/simd/meta/simd_f64x2_arith.py
test/core/simd/simd_f64x2.wast
test/core/simd/simd_f64x2_arith.wast

In running these tests, I discovered that they expected a specific NaN, not a canonical NaN, which causes errors if we always return a canonical NaN of a different sign. As @ngzhian pointed out in a separate conversation, the spec expects the returned value to be a canonical NaN: https://webassembly.github.io/spec/core/bikeshed/index.html#nan-propagation%E2%91%A0. 
@Honry, I don't know if any meta machinery needs to change to generate these files correctly but let me know and I can update the PR.
cc: @arunetm

Fix: assert_return should use canonical NaN for comparison

---

proposals/simd/ImplementationStatus.md

Landed support for 32-bit x86 + support for .bitmask instruction.

Update Firefox/SpiderMonkey status for .bitmask

---

interpreter/text/lexer.mll

The "i32x4" case looks trivial now, but we will be adding i64x2 later.

Create a helper to check valid simd operations

---

proposals/simd/SIMD.md

Clarify that the natural alignment is always the size of the loaded
data.
Resolves #230 and resolves and #162.

Specify the alignment of splatting and extending loads

---

proposals/simd/BinarySIMD.md

Document representation of LandIndxN

---

interpreter/exec/eval_numeric.ml
interpreter/exec/i16.ml
interpreter/exec/int.ml
interpreter/exec/simd.ml
interpreter/exec/v128.ml
interpreter/script/run.ml
interpreter/syntax/operators.ml
interpreter/text/lexer.mll
interpreter/text/parser.mly

Create a new module I16, which uses Int.Make, and is backed by Int32. It
reuses a bunch of logic in Int. It stores 16-bit integers sign-extended
in Int32. This means that -1 (0xFFFF) is stored as 0xFFFFFFFF, rather
than 0x0000FFFF. All the bytes decode/encode logic is also done using
the signed form.

Support i16x8 and implement neg, add, sub, mul

---

interpreter/exec/eval_numeric.ml
interpreter/syntax/operators.ml
interpreter/text/lexer.mll

This passes simd_i8x16_arith2.wast.

Implement 8x16 abs, min_{s,u}, max_{s,u}, avgr_u

---

interpreter/exec/eval_numeric.ml
interpreter/exec/simd.ml
interpreter/exec/v128.ml
interpreter/script/run.ml
interpreter/syntax/operators.ml
interpreter/text/lexer.mll
interpreter/text/parser.mly

Add i64x2.{neg,add,sub,mul}, now simd/simd_i64x2_arith.wast passes.

Support I64x2

---

interpreter/exec/eval_numeric.ml
interpreter/exec/int.ml
interpreter/exec/simd.ml
interpreter/syntax/ast.ml
interpreter/syntax/operators.ml
interpreter/text/lexer.mll

These are implemented in terms of I32x4 operations, since they are
shape agnostic.
Not, and, or, xor, andnot.

Implement v128 bitwise operations

---

document/core/binary/types.rst
document/core/exec/runtime.rst
document/core/intro/overview.rst
document/core/syntax/types.rst
document/core/syntax/values.rst
document/core/text/types.rst
document/core/util/macros.def

This is meant to replace #193 .
Address the feedback given there:
- Issue with using the term "packed integers" in defining the value of 128-bit SIMD. Use i128 instead. Later on, when introducing SIMD instructions, we can add pseudo instructions to convert i128 into the expected lane shapes
- use v128 instead of s128, v128 is used in multiple places, BinarySIMD.md, SIMD.md, reference interpreter, plus s128 already means signed 128-bit integer.
I cherry-picked Deepti's changes from #193, excluding the merge commits, since this PR is rebased on top of master and so already have those changes. The additions/modifications I made are in the latest two commits:
- 4bd26e3ba9d08b6448e0ecdc5b967a948e31b38e
- 8e1bda60cec910c48e1de09c8ca923380226fc01
Looking at only those two might make the review …

Add SIMD type and value

---

interpreter/text/parser.mly

This got lost in the rebase too, and #277 only partially fixed it.

Fix missing parser non-terminal rule for splat

---

.travis.yml

The Bytes [0] functions we use require 4.08.1. This should only be set
on SIMD repo, since bytes is only used for SIMD implementation. By the
time we would like to merge this back into main spec, 4.08.1 should
hopefully be widespread enough for us to bump minimum version of OCaml
for spec to 4.08.1 too.
[0] https://caml.inria.fr/pub/docs/manual-ocaml/libref/Bytes.html see
"Binary encoding/decoding of integers"

Set OCaml version to 4.08.1

---

interpreter/runtime/memory.ml
interpreter/syntax/operators.ml
interpreter/text/lexer.mll

Depends on #281. Please review commit 2e5c9d4 for the changes.
I couldn't figure out a cleaner way to write `load_value`, since `loadn` and `storen` both support 64 bit ints.

v128 load and store

---

interpreter/exec/eval_numeric.ml
interpreter/exec/simd.ml
interpreter/syntax/ast.ml
interpreter/syntax/operators.ml
interpreter/text/lexer.mll

Decided to cheat a little bit, and squeeze v8x16.swizzle into the i8x16
ast node, so that we don't have to create a new v8x16 data type.
Semantically it means the same thing, v8x16 is called that way since it
doesn't treat the underlying data as any particular type, so treating it
as int will work too.
Based on #282 (load and store), review 30a97f8 for changes.

Implement v8x16.swizzle

---

test/core/simd/simd_lane.wast

- lane indices are u8 (nats), negative values are now parse errors ("unexpected token"), as are values with a positive sign `+0x1`
- changed a bunch of "expected i8 literal" to "unexpected token", in order to differentiate these syntax errors we probably need to change the parser to match on a bunch of `EXTRACT_LANE <token we don't care about>`
- some "type mismatch" are now unexpected token
Fixed #287

Update lane index errors

---

test/core/simd/simd_lane.wast

- some test cases were not written in the correct text format
- no more "expected i8 literal", it is now "malformed lane index"
- "v8x16.shuffle (v128.const)" is parsed as shuffle with no literals, so
the error is "invalid lane length"

Fix some of the shuffle related error messages

---

interpreter/binary/decode.ml
interpreter/binary/encode.ml
interpreter/exec/simd.ml
interpreter/exec/v128.ml
interpreter/text/arrange.ml
test/core/run.py

This is sufficient to pass test/core/simd/simd_i32x4_arith.wast.

Implement some binary<-> text support for SIMD

---

interpreter/binary/decode.ml
interpreter/binary/encode.ml
interpreter/text/arrange.ml

This is sufficient to pass test/core/simd/simd_i64x2_arith.wast.

Implement more binary<->text support for SIMD

---

interpreter/binary/decode.ml
interpreter/binary/encode.ml
interpreter/text/arrange.ml

This is sufficient to pass simd_f32x4.wast, simd_f32x4_arith.wast, and
simd_f32x4_cmp.wast.

Implement binary<->text support for SIMD f32x4 arithmetic and compare ops

---

interpreter/binary/decode.ml
interpreter/binary/encode.ml
interpreter/text/arrange.ml

This is sufficient to pass simd_bitwise.wast.

Implement binary<->text support for SIMD bitwise ops

---

interpreter/binary/decode.ml
interpreter/binary/encode.ml
interpreter/text/arrange.ml

This is sufficient to pass simd_boolean.wast.

Implement binary<->text support for SIMD boolean ops

---

interpreter/binary/decode.ml
interpreter/binary/encode.ml
interpreter/text/arrange.ml

This is sufficient to pass simd_load.wast and simd_store.wast. There are
some extra instructions, like swizzle and i8x16.shl that is implemented
here, because simd_load.wast uses them.

Implement binary<->text support for SIMD store and extracts

---

interpreter/binary/decode.ml
interpreter/binary/encode.ml
interpreter/text/arrange.ml

This is sufficient to pass simd_lane.wast.

Implement binary<->text support for SIMD splat and replace

---

interpreter/binary/decode.ml
interpreter/binary/encode.ml
interpreter/text/arrange.ml

This is sufficient to pass simd_splat.wast.

Implement binary<->text support for SIMD saturating ops and some shifts

---

document/core/syntax/instructions.rst
document/core/util/macros.def

Main changes are defining:
- ixx for i8x16, i16x8, i32x4, i64x2
- fxx for f32x4, f64x2
- vxx for ixx and fxx
- the the rest of the SIMD instructions are defined based on these
Unfortunately, the definition of instructions aren't as clean as the existing ones, due to high asymmetry (see https://github.com/WebAssembly/simd/blob/master/proposals/simd/NewOpcodes.md for an overview).
This leads to a lot of specific i8x16, i16x8, i32x4 instructions defined (since i64x2 has to be left out).
I also tweaked the paragraph describing comparisons, to indicate that comparisons can return a boolean, or return a value of the same type, because the SIMD comparisons return S128. I'm not sure if this tweak should stick, we can also classify SIMD comparisons as Binary instructions, but that's confusing too. …

Add SIMD instructions to syntax

---

interpreter/exec/i16.ml
interpreter/exec/i8.ml
interpreter/text/arrange.ml

Print out the full i32 hex string, then extract the lower 2 or 4 chars.

Fix to_hex_string for I8 and I16

---

interpreter/exec/simd.ml
interpreter/script/js.ml
test/core/run.py

V128 is not exposed to JS at all, so transform all functions with V128
in the signatures into consts, compare with the expected value, and
reduce it to a int32. (This is similar to how things are done for i64.)
An assertion against a SimdResult needs to be converted into a plain
Const containing a v128. This conversion is tricky since SimdResult can
contain both LitPat and NanPat. NaNs need special treatment to mask and
compare to a canonical value. For simplicity, we build a mask for all
the patterns in a SimdResult (even for literals, which will have a mask
with all bits set). That way the test is consistent:
- v128.const(mask)
- v128.and
- v128.const(expected)
- i8x16.eq
- i8x16.all_true
- br_if 0 to unreachable

Implement JS output for SIMD

---

interpreter/binary/encode.ml
interpreter/exec/eval.ml
interpreter/exec/simd.ml
interpreter/runtime/memory.ml
interpreter/runtime/memory.mli
interpreter/syntax/ast.ml
interpreter/syntax/operators.ml
interpreter/syntax/types.ml
interpreter/text/arrange.ml
interpreter/text/lexer.mll
interpreter/valid/valid.ml
test/core/simd/simd_align.wast

Add more pack types for SIMD load splat and load extends.
This currently uses the old names, after the sync next week we will decide on #322 and I can add a follow-up patch to address the changes.

Implement SIMD load splat and load extend

---

interpreter/binary/decode.ml
interpreter/binary/encode.ml
interpreter/text/arrange.ml

The names are still pre #297, once that's finalize I can fix this up
(after the sync #323).
With this change, test/core/run.py passes on all test cases in simd/.

Implement binary<->text support for SIMD load splats and extends

---

interpreter/exec/simd.ml
test/core/simd/simd_boolean.wast

Bitmask was confused about endianness. The text format for v128.const is
little endian, so the lowest lane set translates to the least
significant bit set.

Fix SIMD bitmask

---

test/core/run.py

This enables running all the SIMD tests (in test/core/simd) whenever we
do `make test`.
This should not be submitted yet, it depends on #306 or #307 for the
implementation of load splats and loads extends.

Run SIMD tests

---

interpreter/binary/decode.ml
interpreter/syntax/operators.ml
interpreter/text/arrange.ml
interpreter/text/lexer.mll
interpreter/text/parser.mly
proposals/simd/BinarySIMD.md
proposals/simd/ImplementationStatus.md
proposals/simd/NewOpcodes.md
proposals/simd/SIMD.md
proposals/simd/TextSIMD.md
test/core/simd/simd_lane.wast
test/core/simd/simd_load.wast
test/core/simd/simd_splat.wast

v8x16.shuffle and v8x16.swizzle is now i8x16.shuffle and i8x16.swizzle
respectively.
Fixed #316.

Rename shuffle and swizzle to i8x16 prefix

---

document/core/exec/numerics.rst
document/core/syntax/instructions.rst
document/core/text/conventions.rst
document/core/text/instructions.rst
document/core/util/macros.def

Preview this at https://www.ngzhian.com/simd/core/text/instructions.html#simd-instructions

Specify text format for SIMD

---

proposals/simd/BinarySIMD.md
proposals/simd/SIMD.md

Introduction
========
The `f32x4.min`/`f32x4.max`/`f64x2.min`/`f64x2.max` instructions in the WebAssembly SIMD are the natural extensions of the scalar WebAssembly MVP instructions to SIMD instruction sets. These instructions follow JavaScript rules on NaN propagation, i.e. if any operand is NaN, the output is NaN. However, the `min`/`max` operations as defined in the WebAssembly specification have several drawbacks:
1. They have very **asymmetric cost across popular architectures**. E.g. while `f32x4.min` maps to a single instruction (`FMIN Vd.4S, Vn.4S, Vm.4S`) on ARM64, it doesn't have a direct or even a close equivalent in x86 instruction sets. As a result, V8 [has to use 8 SSE2 instructions](https://chromium.googlesource.com/v8/v8.git/+/refs/tags/8.0.12/src/compiler/backend/x64/code-g …

Pseudo-Minimum and Pseudo-Maximum instructions

---

proposals/simd/ImplementationStatus.md

Add pmin/pmax and mark pmin/pmax and floating-point rounding
instructions as implemented on both V8 and SM (based on this
https://github.com/mozilla/gecko-dev/commit/807022887f155153d398f9f6f94ef59e214489a2).

Update implementation status

---

interpreter/binary/encode.ml
interpreter/exec/eval_numeric.ml
interpreter/script/js.ml
interpreter/text/arrange.ml

Replace them with assert false, to indicate that those aren't supposed
to happen, rather than unimplemented.

Clean up some SIMD TODOs

---

proposals/simd/SIMD.md

Per @omnisip, the current wording is confusing as it can be understood as using lane #0 for the output.

Clarify out-of-range behaviour of i8x16.swizzle

---

interpreter/README.md

Replaces #158. @dschuff added 4.08.01 tarball https://wasm.storage.googleapis.com/ as well.
Btw we want 4.08 since we use various functions in https://caml.inria.fr/pub/docs/manual-ocaml/libref/Bytes.html

Update README to require Ocaml 4.08

---

proposals/simd/BinarySIMD.md
proposals/simd/ImplementationStatus.md
proposals/simd/NewOpcodes.md
proposals/simd/SIMD.md

Introduction
=========
This PR introduce two new variants of load instructions which load a **single** 32-bit or 64-bit element into the lowest part of 128-bit SIMD vector and zero-extend it to full 128 bits. These instructions natively map to SSE2 and ARM64 NEON instruction, and have two broad use-cases:
1. Non-contiguous loads, when we need to combine elements from disjoint locations in a single SIMD vector. Non-contiguous loads are commonly emulated by doing loads a single elements and then combining the values through shuffles. While is it possible to do through a combination of scalar loads and `v128.replace_lane` instructions, the resulting code would use be inefficient in using too many general-purpose registers, producing an overly long dependency chain (every `v128.replace_lane` …

v128.load32_zero and v128.load64_zero instructions

---

proposals/simd/BinarySIMD.md
proposals/simd/ImplementationStatus.md
proposals/simd/NewOpcodes.md
proposals/simd/SIMD.md

Introduction
=========
Integer arithmetic instructions in WebAssembly SIMD produce results of the same element type as their inputs. To avoid overflow, developers have to pre-extend inputs to wider element types and do (twice more) arithmetic operations on twice wider elements. The need to use this work-around is particularly concerning for multiplications:
- Unlike additions and subtractions, where overflow is an exceptional situation, multiplications normally produce twice wider result than their inputs, and overflowing input type is a common, rather than exceptional, case. Thus nearly every multiplication must be accompanied by pre-extending inputs to wider element types.
- Both on x86 and on ARM, multiplications which produce twice wider results are cheaper (typically by 2x) than …

i32x4.dot_i16x8_s instruction

---

interpreter/runtime/memory.ml
interpreter/syntax/operators.ml
interpreter/syntax/types.ml
interpreter/text/lexer.mll
test/core/simd/simd_load_zero.wast

The tests are adapted from load_extend tests.
These instructions were merged into the proposal in #237.

Implement v128.load32_zero and v128.load64_zero

---

proposals/simd/ImplementationStatus.md

Dot and LoadZero landed a while back, should be in FF83.

Update SpiderMonkey implementation status

---

document/core/exec/instructions.rst

- `extend` can have types as params, we don't need to take the bitwidth
- bunch of places using `i_1^N` or `i_2^N` can be changed to `i^\ast`

Small cleanup of simd exec/instructions

---

proposals/simd/BinarySIMD.md
proposals/simd/ImplementationStatus.md
proposals/simd/SIMD.md

Introduction
=========
Fixed-point algorithms often represent fractional numbers in [Q format](https://en.wikipedia.org/wiki/Q_(number_format)), where a fixed number of bits is allocated to fractional part. Addition and subtraction in Q format are no different than addition and subtraction on integers, but multiplication is substantially different. First, to produce multiplication result in the same Q format as the factors, we need to compute the full (i.e. with twice the number of bits of the factors) product of the factors, and then do arithmetic shift right by Q bits. Secondly, as the right shift loses some of the bits of the product, it is typically done with rounding to nearest Q-format number to minimize the rounding error. Thus, for Q15 format (i.e. with 15 fractional bits) the …

Saturating Rounding Q-format Multiplication

---

proposals/simd/BinarySIMD.md
proposals/simd/ImplementationStatus.md
proposals/simd/NewOpcodes.md
proposals/simd/SIMD.md

Introduction
=========
This is proposal to add new variant of existing `bitmask` instruction. The new variant extracts the highest bit of the two 64-bit lanes in a SIMD vector into an 32-bit integer. This variant was left out of #201 without any discussion (maybe @zeux knows why), but would be useful both for orthogonality of the instruction set and for efficiency: x86 natively supports this instruction since SSE2, and on ARM is can be emulated more efficiently than other `bitmask` variants.
Applications
=========
- [RTM (RealTime Math) library](https://github.com/nfrechette/rtm/blob/60e61b4fa37b01817e931164a30b21150b260354/includes/rtm/mask4d.h#L133)
- [Havok physics library](https://github.com/resigma/havok-2013/blob/54bc2e0334c526469781fc1186a94f5d850eded4/Common/Base/Math/Vector/Sse/hk …

i64x2.bitmask instruction

---

proposals/simd/BinarySIMD.md
proposals/simd/ImplementationStatus.md
proposals/simd/NewOpcodes.md
proposals/simd/SIMD.md

Introduction
=========
This is proposal to add new variants of existing `widen` instructions. The new variants convert the two low/high 32-bit integers in a SIMD vector to a vector of two 64-bit integers. It is unclear why these variants were left out of #89, as both x86 (since SSE4.1) and ARM NEON include the native equivalents. @AndrewScheidecker asked to reserve opcode space for these instructions, but it seems that there was no discussion about including/excluding the 64-bit forms.
Mapping to Common Instruction Sets
===========================
This section illustrates how the new WebAssembly instructions can be lowered on common instruction sets. However, these patterns are provided only for convenience, compliant WebAssembly implementations do not have to follow the same code …

i64x2.widen_(low/high)_i32x4_(s/u) instructions

---

proposals/simd/BinarySIMD.md
proposals/simd/ImplementationStatus.md
proposals/simd/NewOpcodes.md
proposals/simd/SIMD.md

This patch implements the proposal #416 to make `any_true` instruction untyped as semantically its operation is independent of lane types.

Replace i8x16/i16x8/i32x4.any_true with v128.any_true

---

document/core/binary/instructions.rst
document/core/text/instructions.rst

Follow up to #297 for renaming the instructions in binary and text
sections in the spec.

Fix SIMD load splat/extend names in binary and text section of spec

---

proposals/simd/BinarySIMD.md
proposals/simd/ImplementationStatus.md
proposals/simd/SIMD.md

Introduction
=========
This is proposal to add 64-bit variant of existing `eq` instruction. ARM64 and x86 (since SSE4.1) natively support this instruction, and on ARMv7 NEON and SSE2 is can be efficiently emulated with 3-4 instructions.
Applications
=========
- [Boost.Atomic library](https://github.com/boostorg/atomic/blob/4b2edae1a7dcbd2be1c088ddc05acb0634e69a15/src/find_address_sse41.cpp#L55-L62)
- [SUPERCOP cryptography library](https://github.com/jedisct1/supercop/blob/a4203f1f35c3dac9b96a9ae297f13e22151428e0/crypto_dh/gls254/opt/smu.h#L236-L251)
- [Flang compiler runtime library](https://github.com/flang-compiler/flang/blob/a21454d4a0e27e31743864e389a66b1fd95fbac0/runtime/libpgmath/lib/common/pow/fma3/sdpow.cpp#L115)
- [BearSSL cryptography …

i64x2.eq instruction

---

document/js-api/index.bs

Following the description given in
https://github.com/WebAssembly/simd/blob/master/proposals/simd/SIMD.md#javascript-api-and-simd-values
and also what I64 did before bigint integration.
js-api tests are not updated yet, that will come in a future patch.

Add v128 to JS API

---

interpreter/Makefile

We list all simd test cases in simd/* in TESTFILES, then tweak the
substitution in quiettest to strip quiettest/ from the front of the
target, rather than match on just the file name (which loses the simd/)
prefix.
The temp output file name is unchanged, it uses the base file name (no
simd/ prefix).

Run simd test cases with make partest

---

document/core/binary/instructions.rst
document/core/exec/instructions.rst
document/core/syntax/instructions.rst
document/core/text/instructions.rst
document/core/valid/instructions.rst

These instructions load 32/64 bits, then zero-extends them to the full 128 bits. The formalization thus use unsigned extensions to specify these instructions.

[spectext] Add semantics for v128.load32_zero v128.load64_zero

---

interpreter/binary/decode.ml
interpreter/binary/encode.ml
interpreter/exec/eval_simd.ml
interpreter/syntax/operators.ml
interpreter/text/arrange.ml
interpreter/text/lexer.mll
test/core/simd/simd_boolean.wast

This was accepted into this proposal in #410.

Implement i64x2.bitmask (#368)

---

proposals/simd/BinarySIMD.md
proposals/simd/ImplementationStatus.md
proposals/simd/SIMD.md

Introduction
=========
The PR introduce a SIMD variant of Population Count operation. This operation counts the number of bits set to 1, is commonly used in algorithms involving Hamming distance between two binary vectors. Population Count is represented in the scalar WebAssembly instruction set, and many native SIMD instruction sets. E.g. ARM NEON and AVX512BITALG extensions natively support the 8-bit lane variant introduced in this proposal. Implementation in SSSE3 is less trivial, but still more efficient than emulation with `i8x16.swizzle` instruction due to elimination of `PADDUSB` instruction and direct lowering of table lookups into `PSHUFB`. Moreover, the SIMD Population Count can be efficiently implemented on SSE2-level processors where `i8x16.swizzle`-based emulation would have …

Population count instruction

---

document/core/syntax/instructions.rst

Previously it was included \ishape.\virelop, but it is incorrect, as we
don't have i64x2 unsigned comparisons.
i64x2 unsigned comparisons were added in #412.

[spectext] Add i64x2 eq,ne,lt_s,gt_s,le_s,ge_s.

---

document/core/exec/instructions.rst
document/core/syntax/instructions.rst
document/core/util/macros.def
document/core/valid/instructions.rst

These instructions were merged in #376.

[spectext] Add ext mul instructions

---

document/core/syntax/instructions.rst
document/core/util/macros.def

It maps nicely to the existing vunop group, so the validation and
execution semantics are taken care of.
Drive-by fixes:
- was using NEG instead of VNEG for SIMD negation instruction
- vunop includes neg twice, since viunop already includes neg.

[spectext] Add i8x16.popcnt to syntax

---

interpreter/Makefile

Follow-up to #434.
Now `make partest && make partest` shouldn't fail.

Skip _output directory when listing wast files for test.

---

document/core/syntax/instructions.rst

This is a simple change, validation and execution is already
shape-agnostic, so we only need to add it to the syntax.
Instructions were merged in #290.

[spectext] Add i64x2.widen_{low,high}_i32x4_{s,u} to syntax

---

document/core/exec/instructions.rst
document/core/syntax/instructions.rst
document/core/util/macros.def
document/core/valid/instructions.rst

Load lane and store lane instructions added in #350.

[spectext] Load lane and store lane validation and semantics

---

interpreter/binary/decode.ml
interpreter/binary/encode.ml
interpreter/exec/eval_simd.ml
interpreter/syntax/operators.ml
interpreter/text/arrange.ml
interpreter/text/lexer.mll
test/core/simd/meta/simd_int_arith2.py
test/core/simd/simd_i16x8_arith2.wast

[interpreter] Implement i64x2.abs

---

interpreter/binary/decode.ml
interpreter/binary/encode.ml
interpreter/exec/eval_simd.ml
interpreter/syntax/operators.ml
interpreter/text/arrange.ml
interpreter/text/lexer.mll
test/core/simd/simd_boolean.wast

[interpreter] Add i64x2.all_true

---

test/core/simd/simd_i64x2_arith2.wast

Missed adding this when implementing i64x2.abs.

Check in simd_i64x2_arith2.wast test file

---

document/core/binary/instructions.rst

It looks like these have a typo in copying them over from
`BinarySIMD.md`

Fix a typo in the f64x2.{pmin,pmax} binary spec

---

document/core/exec/instructions.rst
document/core/syntax/instructions.rst
document/core/util/macros.def
document/core/valid/instructions.rst

SIMD comparisons return -1 (all bits set) in the lanes. Currently as
specified, they return 1 (since we use the numeric comparison). We fix
this by extracting these instructions (virelop and vfrelop) into vrelop,
and in the execution, sign extend them from i1 to iX (which treats the
1-bit integer "1" as -1).
Drive-by fix for exec-vbinop, some typos in the execution semantics.
Fixed #441.

Comparison instructions should return -1 in lanes

---

document/core/exec/instructions.rst

\extend takes the bitwidth of type, but we have been passing the number
of lanes, i.e. for i64x2, we should be passing 64, not 2.

Fix usages of \extend in SIMD instructions

---

interpreter/script/js.ml
interpreter/script/run.ml
interpreter/script/script.ml
interpreter/text/arrange.ml
interpreter/text/parser.mly

Took the chance to clean up the matching logic for SimdResult too.

Small cleanup to num_pat to remove redundant Source.phrase

---

proposals/simd/ImplementationStatus.md

The proposal is fully implemented as of V8 9.1. Also removed a footnote about instruction availability in M87.

Update V8 implementation status

---

document/core/appendix/index-types.rst
document/core/binary/conventions.rst
document/core/exec/runtime.rst
document/core/intro/overview.rst
document/core/text/conventions.rst
document/core/util/macros.def

Based on comments from https://github.com/WebAssembly/spec/pull/1391.

Fix some stale references to value types
