WebAssembly/simd

README.md, proposals/simd/Overview.md
This makes it easier to find the proposed changes at a glance.
=> Move the contents of Overview.md to the top-level README file.

proposals/simd/SIMD.md
These got missed when the other operations were renamed.
=> Change the lane access operations to snake_case.

meetings/meeting-4-24-19.md
Organizing sync notes into a 'meeting' folder for future reference.
=> Organizing sync notes into a 'meeting' folder for future reference. 

test/core/simd/simd_splat.wast
https://github.com/WAVM/WAVM/pull/225
[simd] Add more literal tests for splat ops
Part of https://github.com/WAVM/WAVM/issues/195
=> [test] Sync tests from WAVM#225

proposals/simd/ImplementationStatus.md
Add swizzle and avgr_u, update flag for integer min/max.
=> Update LLVM implementation status

test/core/simd/simd_align.wast
Tests are synced from https://github.com/WAVM/WAVM/pull/251
=> [test] Test more alignment for load extend and splat ops

interpreter/exec/eval_numeric.ml, interpreter/exec/simd.ml, interpreter/exec/v128.ml, interpreter/script/run.ml, interpreter/syntax/ast.ml, interpreter/syntax/operators.ml, interpreter/text/lexer.mll, interpreter/text/parser.mly
And enough operations to pass the simd_f64x2.wast test.
=> Implement v128.const parsing for f64x2 with nans

proposals/simd/ImplementationStatus.md
Currently Nightly x64 only, and with limited optimizations.  More optimizations + x86 are in the pipeline and will land over the next weeks.  No definite schedule for arm64 or arm at this time.
=> Add SpiderMonkey implementation status

proposals/simd/BinarySIMD.md
=> Use ImmLaneIdx consistently

interpreter/exec/eval_numeric.ml, interpreter/exec/i8.ml, interpreter/exec/simd.ml, interpreter/exec/v128.ml, interpreter/script/run.ml, interpreter/syntax/operators.ml, interpreter/text/lexer.mll, interpreter/text/parser.mly
Implement add sub neg for i8x16, this passes simd_i8x16_arith.wast.
=> Add i8x16 support

interpreter/.merlin
Really simple merge, just wanted to get the .merlin file from upstream here so I don't have to have untracked files locally :)
=> Merge upstream

interpreter/text/parser.mly
Lost the token in the parser during rebases.
=> Fix parsing of splat

interpreter/exec/eval_numeric.ml, interpreter/exec/simd.ml, interpreter/syntax/ast.ml, interpreter/syntax/operators.ml, interpreter/text/lexer.mll, interpreter/text/parser.mly, interpreter/valid/valid.ml
Depends on #288 and #291, review ac03a3d for changes.
=> Implement shuffle

interpreter/exec/int.ml
Addressing comments on https://github.com/WebAssembly/simd/pull/311
=> Formatting fixes in shr_u

interpreter/binary/decode.ml, interpreter/binary/encode.ml, interpreter/text/arrange.ml
Adding all shr_u and also i64x2 shifts.
=> Complete binary<->text for SIMD shifts

interpreter/syntax/ast.ml
Addresses https://github.com/WebAssembly/simd/pull/307#discussion_r489261485
=> Remove rhs from emtpy type

document/core/exec/numerics.rst, document/core/text/instructions.rst
Also formatting of SIMD instructions
=> Inline bytes expansion into text format

document/core/binary/instructions.rst, document/core/syntax/instructions.rst, document/core/util/macros.def
Also fix up the definition in the syntax to be a u4 instead of a byte.
=> Create Blaneidx production, and encode lane index as u8

proposals/simd/ImplementationStatus.md
Clarify SIMD availability in different Firefox channels.
=> Tweak Firefox implementation status

proposals/simd/ImplementationStatus.md
For i64x2.bitmask and ext_mul instructions.
=> Update v8 implementation status

interpreter/exec/simd.ml
=> [interpreter] Add a missing closing parens

proposals/simd/ImplementationStatus.md
All instructions now implemented in latest Nightly.
=> Update SpiderMonkey implementation status

test/js-api/global/constructor.any.js
=> Add simple JS api test for SIMD

proposals/simd/SIMD.md
=> Name memarg arguments
